version: '3'
services:
  postgres01:
    image: postgres:14.3-alpine
    container_name: postgres01
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: postgres01
      POSTGRES_USER: postgres01
      POSTGRES_PASSWORD: postgres01
    volumes:
      - ./db/postgres01:/docker-entrypoint-initdb.d
  postgres02:
    image: postgres:14.3-alpine
    container_name: postgres02
    ports:
      - "5002:5432"
    environment:
      POSTGRES_DB: postgres02
      POSTGRES_USER: postgres02
      POSTGRES_PASSWORD: postgres02
    volumes:
      - ./db/postgres02:/docker-entrypoint-initdb.d
